### ISSUE TITLE
劲洁兄，这个问题何解？

### ISSUE THREAD

**Issue by hack2012** [lijiejie/subDomainsBrute#1]
此工具在windows下使用，老是会出问题，兄弟可有解决办法？
![dns](https://cloud.githubusercontent.com/assets/3817100/11627705/a5d64a4c-9d27-11e5-9806-2b82cd6473bb.png)
报错如图，我在win10及win7下均出现过此问题。win10 python2.7.10 x64位的。

**Comment by lijiejie** [comment]
检查下是不是字典中出现了中文？  稍后我检查下容错

**Comment by hack2012** [comment]
字典我使用的是自带的，你原本就有的。linux下面正常的。

**Comment by lijiejie** [comment]
我这两天会处理修复下，之前有别的同学也遇到类似编码的问题了。  感谢反馈   :)
