### ISSUE TITLE
有强迫症的我来请教一下

### ISSUE THREAD

**Issue by ghost** [lijiejie/subDomainsBrute#10]
先反映一个疑似笔误的地方，在文件subDomainsBrute.py的第292行位置的d，应该是self吧。
` d.resolvers[thread_id].query('lijiejietest.' + cur_sub_domain)`
应该是：
` self.resolvers[thread_id].query('lijiejietest.' + cur_sub_domain)`
然后，我想请教一下，这里的查询lijiejietest.xxxx域名，这里的捕获NXDOMAIN的异常，是用来干什么的呢？不是很理解这里的思路呢？麻烦解答一下，十分感谢！！

**Comment by lijiejie** [comment]
感谢，我这修改一下。 lijiejietest.去测试一个不存在的域名，能正常解析，表明DNS服务器存在异常，可能是恶意DNS。
