### ISSUE TITLE
VMware Fusion中Ubuntu 14.04 LTS 遇到错误关闭虚拟机

### ISSUE THREAD

**Issue by 0x554simon** [lijiejie/subDomainsBrute#11]
在MAC下Fusion中的Ubuntu跑subDomainBrute一小段时间后，Fusion提示虚拟机遇到错误已经关闭。

**Comment by lijiejie** [comment]
可以比较稳定地复现吗？  试试获取最新的脚本

**Comment by 0x554simon** [comment]
OK,可能是MAC下的虚拟机有问题，虚拟网卡跑挂了
