### ISSUE TITLE
在windows 下的cmd  执行出错， 在powershell  python.exe 一闪而过

### ISSUE THREAD

**Issue by Sunfcy** [lijiejie/subDomainsBrute#14]
你好， 我遇到了一下情况，不知道是哪里出错了， python 的环境变量是没有问题的 。
`C:\软件包\subDomainsBrute-master>python subDomainsBrute.py  baidu.com
Traceback (most recent call last):
  File "subDomainsBrute.py", line 9, in <module>
    import gevent
ImportError: No module named gevent`

我确定不是中文路劲的问题。
[如图](http://oh5ewp410.bkt.clouddn.com/TIM%E5%9B%BE%E7%89%8720170613110605.png)

**Comment by MythHack** [comment]
No module named gevent

**Comment by lijiejie** [comment]
pip install gevent

**Comment by Sunfcy** [comment]
thanks !
