### ISSUE TITLE
两台电脑两个网络都是一样的结果 - -我买的VPS就正常，换了好多DNS都没法，

### ISSUE THREAD

**Issue by bubaidongfang** [lijiejie/subDomainsBrute#15]
[+] Validate DNS servers ...
[+] Check DNS Server 223.5.5.5        <Fail>   Found 0
[+] Found 0 available DNS Servers in total
[ERROR] No DNS Servers available.

**Comment by lijiejie** [comment]
可以修改  dict/dns_servers.txt  配置一下你可用的DNS服务器
