### ISSUE TITLE
关于子域名爆破次序，提高效率的问题

### ISSUE THREAD

**Issue by starnightcyber** [lijiejie/subDomainsBrute#18]
lijiejie ~ 李哥哥，有点问题想请教一下
1、给定一个域名，比如说baidu.com, 您的代码中是爆破两级子域名，讲道理应该先爆破子一级域名，即sub.baidu.com, 得到一些有效的子域名列表【sub.baidu.com】之后，再爆破
next_sub.【sub.baidu.com】，得到所有一二级子域名，这样效率才会更高。
2、但我在您的代码中没有明显看到这样一个逻辑，你还提到“增加了占位符{next_sub}”， 认真阅读过您的代码，只在代码287行添加了{next_sub}， 在227行做了替换，而且还是测试一个“不存在的lijiejietest”， 这样好像之后会有更多的query， 我不太明白这样做的意图？ 或许是想做一个这样的： {next_sub}.sub.baidu.com， 进行二级子域名检探测， 是想跟第1点一样吗？
烦请解答，多谢！

**Comment by starnightcyber** [comment]
在大佬的工作基础上，我删除了一些复杂的代码，并添加了相应的注释，使得代码看起来更加简单明了，程序运行的速度更快，而且能找到更多有效的子域名（虽然很多是解析到同一个ip， 但确实是有效的域名，当然也没有一一检测）。
烦请大佬有空的时候帮忙指导一下：https://github.com/starnightcyber/findSubDomains
下面是猜解qq.com最终的运行结果：[二级子域名]
4265 subnames found in total 
Results are saved to threes files starts with ['qq.com'] 
Program running 951.4 seconds

**Comment by lijiejie** [comment]
赞，我今天抽空先试用和对比一下。

**Comment by lijiejie** [comment]
把去重的部分修改了吗？  

$ awk -F "\t" '{print $2}' qq.com.txt |sort|uniq|wc -l
508

我看这个qq.com.txt， * 3大概也是 1500的域名

**Comment by starnightcyber** [comment]
qq.com.txt 文件中保存的是子域名和ip， 您上面给的去重是对ip地址去重，我确实没有对ip进行去重（我后面再改下），您将2->1 试试， 哪些是放在set()里面的子域名，应该不存在重复项。

**Comment by lijiejie** [comment]
感谢 @starnightcyber  你可以再参考一下新的版本，做一些改进
