### ISSUE TITLE
求助：执行报错 149 行

### ISSUE THREAD

**Issue by buoren2316** [lijiejie/subDomainsBrute#20]
python subDomainsBrute.py qq.com
  File "subDomainsBrute.py", line 149
    tmp_set = {sub}
                  ^
SyntaxError: invalid syntax

**Comment by lijiejie** [comment]
请检查一下python -V， 这个脚本需要python2.7     你可以试试   python2.7 subDomainsBrute.py qq.com

**Comment by 687766616e** [comment]
$ python subDomainsBrute.py qq.com
  File "subDomainsBrute.py", line 149
    except dns.resolver.NoAnswer, e:
                                ^
SyntaxError: invalid syntax
$ python2 subDomainsBrute.py qq.com
Traceback (most recent call last):
  File "subDomainsBrute.py", line 10, in <module>
    import gevent
ImportError: No module named gevent
$ python2.7 subDomainsBrute.py qq.com
Traceback (most recent call last):
  File "subDomainsBrute.py", line 10, in <module>
    import gevent
ImportError: No module named gevent

**Comment by starnightcyber** [comment]
pip install dnspython gevent
