### ISSUE TITLE
关于域名泛解析的建议

### ISSUE THREAD

**Issue by victor-infosec** [lijiejie/subDomainsBrute#25]
大牛好！这个工具非常不错~
建议在爆破子域名的时候，可以增加泛解析的判断，区分域名被泛解析到同一IP，哪些不是。只保留不被泛解析的域名。^_^

**Comment by lijiejie** [comment]
谢谢你的反馈，原来检查过子三级以上域名的泛解析。  
目前增加了二级域名的检查了。
