### ISSUE TITLE
macos 下pip dnspython失败

### ISSUE THREAD

**Issue by pygain11** [lijiejie/subDomainsBrute#27]
macos 下 非root权限使用
pip install dnspython gevent --user -U 能够成功pip

**Comment by albertofwb** [comment]
我遇到了同样的问题,后来使用 virtualenv 解决了
```bash
sudo pip install virtualenv
virtualenv py2
source py2/bin/active

pip install gevent
```

**Comment by odboy** [comment]
> macos 下 非root权限使用
> pip install dnspython gevent --user -U 能够成功pip

成功解决问题，但为什么呢？

**Comment by albertofwb** [comment]
@odboy 因为 --user 的意思是将包安装在用户目录下，所以不存在权限问题
-U, --upgrade               Upgrade all specified packages to the newest available version. The handling of dependencies depends on the upgrade-strategy used.

具体可以执行如下命令查看各个参数的含义
``` bash
$ pip install -h
```

参考这里：
https://havee.me/mac/2014-05/individual-scheme-for-pip.html
https://segmentfault.com/q/1010000004177357

**Comment by lijiejie** [comment]
感谢大家的讨论和总结。  请遇到同类问题的同学参考
