### ISSUE TITLE
Bug 扫描部分域名没有结果

### ISSUE THREAD

**Issue by notwhy** [lijiejie/subDomainsBrute#39]
如下：
1.python subDomainsBrute.py meizu.com
  SubDomainsBrute v1.2
  https://github.com/lijiejie/subDomainsBrute

[+] Validate DNS servers
[+] Server 119.29.29.29     < OK >   Found 4
[+] 4 DNS Servers found
[+] Run wildcard test
any-sub.meizu.com                     	115.28.238.198

2.python subDomainsBrute.py meizu.cn
  SubDomainsBrute v1.2
  https://github.com/lijiejie/subDomainsBrute

[+] Validate DNS servers
[+] Server 114.114.114.114  < OK >   Found 4
[+] 4 DNS Servers found
[+] Run wildcard test
any-sub.meizu.cn                      	115.28.238.198
3. python subDomainsBrute.py guahao.com
  SubDomainsBrute v1.2
  https://github.com/lijiejie/subDomainsBrute

[+] Validate DNS servers
[+] Server 114.114.114.114  < OK >   Found 4
[+] 4 DNS Servers found
[+] Run wildcard test
any-sub.guahao.com                    	42.81.85.241, 42.81.92.60, 42.81.92.66

都没有结果 希望查明下原因

**Comment by starnightcyber** [comment]
any-sub.meizu.cn xx.xx.xx.xx
意思就是任意命名的子域名都会解析到某个ip。

**Comment by notwhy** [comment]
@starnightcyber 这个检测感觉还是有点问题的啊,是不是认定太宽松了点。
ping lists.meizu.com
PING lists.meizu.com (203.107.32.146): 56 data bytes
64 bytes from 203.107.32.146: icmp_seq=0 ttl=52 time=30.863 ms
64 bytes from 203.107.32.146: icmp_seq=1 ttl=52 time=31.003 ms
ping care.meizu.com
PING care.meizu.com (203.107.32.146): 56 data bytes
64 bytes from 203.107.32.146: icmp_seq=0 ttl=52 time=32.544 ms
64 bytes from 203.107.32.146: icmp_seq=1 ttl=52 time=30.724 ms
ping aaaa.meizu.com
PING aaaa.meizu.com (115.28.238.198): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
ping sec.meizu.com
PING sec.meizu.com (14.29.125.185): 56 data bytes
64 bytes from 14.29.125.185: icmp_seq=0 ttl=50 time=41.781 ms
64 bytes from 14.29.125.185: icmp_seq=1 ttl=50 time=41.227 ms

**Comment by mumu0215** [comment]
同问！

**Comment by MaestroPajero** [comment]
Same error whit some domains idk why

**Comment by 2077himasi** [comment]
同问！+1

**Comment by kejaly** [comment]
我有些也是这样

**Comment by luckybool1020** [comment]
我也有这个问题，怎么解决啊？

**Comment by lijiejie** [comment]
多谢大家反馈，今天处理一下。  允许扫描这类存在泛解析的域名

**Comment by lijiejie** [comment]
已经处理了，大家可以试试git pull  ， 加-w 参数
