### ISSUE TITLE
jiejie 可否处理下泛解析

### ISSUE THREAD

**Issue by leezp** [lijiejie/subDomainsBrute#42]
将结果整理下，泛解析的站结果太多，

**Comment by lijiejie** [comment]
是否有相应的例子用来测试？ 最近自己很少再使用了

**Comment by leezp** [comment]
有的，例如：

tube8.com    泛解析
brave.com  过多泛解析
flickr.com  百万泛解析
binary.com   百万 泛解析

**Comment by leezp** [comment]
我的处理方式是把lijijie子域爆破工具输出的小于 10k的结果汇聚，输出结果过多的文件将它按状态码(https://github.com/leezp/SubdomainWash/blob/master/statusCodeClean.py)
和内容差异
(https://github.com/leezp/SubdomainWash/blob/master/subdomainClean.py)
清洗。

**Comment by lijiejie** [comment]
git pull 试试 加 -w 参数，处理了一下泛解析

**Comment by leezp** [comment]
@lijiejie  cool

**Comment by leezp** [comment]
fast and cool
