### ISSUE TITLE
扫描不到域名

### ISSUE THREAD

**Issue by EmptyHell** [lijiejie/subDomainsBrute#45]
![image](https://user-images.githubusercontent.com/58494744/81262192-ed95ab80-906f-11ea-91b4-92c11e9282e7.png)

**Comment by lijiejie** [comment]
可提供系统和python的版本号

**Comment by EmptyHell** [comment]
>python3 -V
Python 3.7.4

>uname -a
Linux x 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

**Comment by lijiejie** [comment]
还存在这样的现象吗？
