### ISSUE TITLE
请问为啥源代码里面domain不直接拿来用，还要经过aiodns库query查询一个不存在的域名这个过程？

### ISSUE THREAD

**Issue by goodwozou** [lijiejie/subDomainsBrute#49]

**Comment by goodwozou** [comment]
关键问题是query查询不存在的域名有时能够返回ip有时会发出异常？这是为啥？

**Comment by Evilran** [comment]
> 关键问题是query查询不存在的域名有时能够返回ip有时会发出异常？这是为啥？

猜测 query 是用来探测 cur_domain 域名下存不存在子域名的，比如  www.target.com -> lijiejie-test-not-existed.www.target.com

**Comment by lijiejie** [comment]
如果不存在的域名也能解析成功，这样的DNS服务器不可靠，是无法使用的
