### ISSUE TITLE
线程默认是60，而且对线程的处理有一处小问题

### ISSUE THREAD

**Issue by leveryd** [lijiejie/subDomainsBrute#5]
def run(self):
        self.start_time = time.time()
        for i in range(self.threads_num):
            t = threading.Thread(target=self._scan, name=str(i))
            t.setDaemon(True)
            t.start()
        while self.thread_count > 1:
            try:
                time.sleep(1.0)
这儿的self.thread_count应该是self.thread_count > 0吧

**Comment by lijiejie** [comment]
可试试新的脚本
