### ISSUE TITLE
AttributeError: 'GenericRdata' object has no attribute 'target'

### ISSUE THREAD

**Issue by bloodzer0** [lijiejie/subDomainsBrute#50]
Python2执行报错：AttributeError: 'GenericRdata' object has no attribute 'target'

**Comment by lijiejie** [comment]
是否还能复现？

**Comment by luckybool1020** [comment]
> 是否还能复现？

还能啊

**Comment by luckybool1020** [comment]
> > 是否还能复现？
> 
> 还能啊

不知道为啥刚才出现了这个问题，再跑第二遍又没有了。
