### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by geelph** [lijiejie/subDomainsBrute#55]
2020年9月27日git新版subDomainBrute源码到本地测试。
python2测试：
环境：
- Windows 10
- python27
安装dnspython和gevent模块后爆破baidu.com运行正常。
![python2](https://gitee.com/jixiansiwei/ImagesBed/raw/master/Security/InfoGathering/Domain/subDomainBrute爆破结束.png)

但是在python3测试时发生错误致使运行异常终止。
python3测试：
环境：
- Windows 10
- python38
安装aiodns模块后爆破baidu.com，程序异常终止。
![python3](https://gitee.com/jixiansiwei/ImagesBed/raw/master/Security/InfoGathering/Domain/python3执行程序异常终止.png)

报错提示信息为：ValueError: too many file descriptors in select()
百度该类报错信息，推测可能是多线程并发执行未控制好。
请教那位师傅能具体说一下报错的原因及解决办法。

**Comment by lijiejie** [comment]
多谢报告，我这边找环境调试一下

**Comment by lijiejie** [comment]
已经定位到原因，是因为配置了多个DNS服务器，有的协程维护了大于1个连接。
导致超过进程允许打开的连接数量。 稍后会修复这个问题

**Comment by lijiejie** [comment]
已处理修复了，可git pull试试

**Comment by geelph** [comment]
OK，已git运行良好
