### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Secxt** [lijiejie/subDomainsBrute#65]
root@VM-16-7-ubuntu:~/subDomainsBrute-1.1# python3 subDomainsBrute.py -h
  File "subDomainsBrute.py", line 149
    except dns.resolver.NoAnswer,e:
                                ^
SyntaxError: invalid syntax

**Comment by lijiejie** [comment]
看起来版本不对，是最新的吗？  因为这个文件看起来没有149行。
可以试试重新git pull
