### ISSUE TITLE
两个多线程的问题想请教前辈

### ISSUE THREAD

**Issue by Xyntax** [lijiejie/subDomainsBrute#7]
2 为什么项目里不设计成deamon+Ctrl-C直接杀掉所有子线程,而是要等待子线程退出呢?
3 如果在子线程中调用了一个函数,想让这个函数超时return或者raise
考虑到import signal无法用于子线程,如果把函数扔进线程A里,再另开一个线程B做监控,超时之后杀A,这样线程数量开销较大.而且杀线程总怕影响到未释放的系统资源,有更好的方案吗?

期待大牛传授经验,谢啦^_^

**Comment by lijiejie** [comment]
时间过得太久了些，现在是多进程的形式了。抱歉，没有能够及时回复

你的意思是通过setDaemon之类的方式，让子线程随着main thread直接退出了对吗？

之前我还是较多地，通过一个全局变量来控制，比如STOP_ME，然后控制好这个子线程里面每一行能够被确保执行完成，能够有机会被超时终止。

**Comment by Xyntax** [comment]
哈哈，收到，发现过去好久了
