### ISSUE TITLE
结果有遗漏

### ISSUE THREAD

**Issue by an9er** [lijiejie/subDomainsBrute#9]
800线程跑163.com的子域名的时候相同的字典（非默认）找到399个，而用dnsdict跑415个。

**Comment by an9er** [comment]
并且多跑几次相同字典结果也不唯一，399,408...

**Comment by an9er** [comment]
只是进行xxx.163.com 不进行更深层的枚举

**Comment by an9er** [comment]
原因 : 由timeout导致

**Comment by an9er** [comment]
解决方法:
是否可以考虑把timeout6次之后的domain字段重新加入queue中

**Comment by lijiejie** [comment]
早前处理timeout了，目前又去掉。 可试试git pull获取新的代码，再看看效果
